services:
  app:
    build: .
    command: python -u app.py
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    links:
      - db
  db:
    image: mongo:latest
    hostname: records_mongodb
    environment:
      - MONGO_INITDB_DATABASE=records_db
      - MONGO_INITDB_ROOT_USERNAME=adminuser
      - MONGO_INITDB_ROOT_PASSWORD=adminpass1234
    volumes:
      - .:/app/data
    ports:
      - 27017:27017
